// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

#include "add.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rpc {
PROTOBUF_CONSTEXPR AddMethod::AddMethod(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.arg1_)*/0
  , /*decltype(_impl_.arg2_)*/0
  , /*decltype(_impl_.ret1_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AddMethodDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddMethodDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddMethodDefaultTypeInternal() {}
  union {
    AddMethod _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddMethodDefaultTypeInternal _AddMethod_default_instance_;
}  // namespace rpc
static ::_pb::Metadata file_level_metadata_add_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_add_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_add_2eproto = nullptr;

const uint32_t TableStruct_add_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rpc::AddMethod, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rpc::AddMethod, _impl_.arg1_),
  PROTOBUF_FIELD_OFFSET(::rpc::AddMethod, _impl_.arg2_),
  PROTOBUF_FIELD_OFFSET(::rpc::AddMethod, _impl_.ret1_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rpc::AddMethod)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rpc::_AddMethod_default_instance_._instance,
};

const char descriptor_table_protodef_add_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tadd.proto\022\003rpc\"5\n\tAddMethod\022\014\n\004arg1\030\001 "
  "\001(\005\022\014\n\004arg2\030\002 \001(\005\022\014\n\004ret1\030\003 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_add_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_add_2eproto = {
    false, false, 79, descriptor_table_protodef_add_2eproto,
    "add.proto",
    &descriptor_table_add_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_add_2eproto::offsets,
    file_level_metadata_add_2eproto, file_level_enum_descriptors_add_2eproto,
    file_level_service_descriptors_add_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_add_2eproto_getter() {
  return &descriptor_table_add_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_add_2eproto(&descriptor_table_add_2eproto);
namespace rpc {

// ===================================================================

class AddMethod::_Internal {
 public:
};

AddMethod::AddMethod(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rpc.AddMethod)
}
AddMethod::AddMethod(const AddMethod& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AddMethod* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.arg1_){}
    , decltype(_impl_.arg2_){}
    , decltype(_impl_.ret1_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.arg1_, &from._impl_.arg1_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ret1_) -
    reinterpret_cast<char*>(&_impl_.arg1_)) + sizeof(_impl_.ret1_));
  // @@protoc_insertion_point(copy_constructor:rpc.AddMethod)
}

inline void AddMethod::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.arg1_){0}
    , decltype(_impl_.arg2_){0}
    , decltype(_impl_.ret1_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AddMethod::~AddMethod() {
  // @@protoc_insertion_point(destructor:rpc.AddMethod)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AddMethod::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AddMethod::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AddMethod::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc.AddMethod)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.arg1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ret1_) -
      reinterpret_cast<char*>(&_impl_.arg1_)) + sizeof(_impl_.ret1_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddMethod::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 arg1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.arg1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 arg2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.arg2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 ret1 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ret1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AddMethod::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc.AddMethod)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 arg1 = 1;
  if (this->_internal_arg1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_arg1(), target);
  }

  // int32 arg2 = 2;
  if (this->_internal_arg2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_arg2(), target);
  }

  // int32 ret1 = 3;
  if (this->_internal_ret1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_ret1(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc.AddMethod)
  return target;
}

size_t AddMethod::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc.AddMethod)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 arg1 = 1;
  if (this->_internal_arg1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_arg1());
  }

  // int32 arg2 = 2;
  if (this->_internal_arg2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_arg2());
  }

  // int32 ret1 = 3;
  if (this->_internal_ret1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ret1());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddMethod::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AddMethod::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddMethod::GetClassData() const { return &_class_data_; }


void AddMethod::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AddMethod*>(&to_msg);
  auto& from = static_cast<const AddMethod&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc.AddMethod)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_arg1() != 0) {
    _this->_internal_set_arg1(from._internal_arg1());
  }
  if (from._internal_arg2() != 0) {
    _this->_internal_set_arg2(from._internal_arg2());
  }
  if (from._internal_ret1() != 0) {
    _this->_internal_set_ret1(from._internal_ret1());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AddMethod::CopyFrom(const AddMethod& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc.AddMethod)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddMethod::IsInitialized() const {
  return true;
}

void AddMethod::InternalSwap(AddMethod* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AddMethod, _impl_.ret1_)
      + sizeof(AddMethod::_impl_.ret1_)
      - PROTOBUF_FIELD_OFFSET(AddMethod, _impl_.arg1_)>(
          reinterpret_cast<char*>(&_impl_.arg1_),
          reinterpret_cast<char*>(&other->_impl_.arg1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AddMethod::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_add_2eproto_getter, &descriptor_table_add_2eproto_once,
      file_level_metadata_add_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rpc::AddMethod*
Arena::CreateMaybeMessage< ::rpc::AddMethod >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rpc::AddMethod >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
