// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_add_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_add_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_add_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_add_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_2eproto;
namespace rpc {
class AddMethod;
struct AddMethodDefaultTypeInternal;
extern AddMethodDefaultTypeInternal _AddMethod_default_instance_;
}  // namespace rpc
PROTOBUF_NAMESPACE_OPEN
template<> ::rpc::AddMethod* Arena::CreateMaybeMessage<::rpc::AddMethod>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rpc {

// ===================================================================

class AddMethod final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rpc.AddMethod) */ {
 public:
  inline AddMethod() : AddMethod(nullptr) {}
  ~AddMethod() override;
  explicit PROTOBUF_CONSTEXPR AddMethod(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddMethod(const AddMethod& from);
  AddMethod(AddMethod&& from) noexcept
    : AddMethod() {
    *this = ::std::move(from);
  }

  inline AddMethod& operator=(const AddMethod& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddMethod& operator=(AddMethod&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddMethod& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddMethod* internal_default_instance() {
    return reinterpret_cast<const AddMethod*>(
               &_AddMethod_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddMethod& a, AddMethod& b) {
    a.Swap(&b);
  }
  inline void Swap(AddMethod* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddMethod* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddMethod* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddMethod>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddMethod& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddMethod& from) {
    AddMethod::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddMethod* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rpc.AddMethod";
  }
  protected:
  explicit AddMethod(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArg1FieldNumber = 1,
    kArg2FieldNumber = 2,
    kRet1FieldNumber = 3,
  };
  // int32 arg1 = 1;
  void clear_arg1();
  int32_t arg1() const;
  void set_arg1(int32_t value);
  private:
  int32_t _internal_arg1() const;
  void _internal_set_arg1(int32_t value);
  public:

  // int32 arg2 = 2;
  void clear_arg2();
  int32_t arg2() const;
  void set_arg2(int32_t value);
  private:
  int32_t _internal_arg2() const;
  void _internal_set_arg2(int32_t value);
  public:

  // int32 ret1 = 3;
  void clear_ret1();
  int32_t ret1() const;
  void set_ret1(int32_t value);
  private:
  int32_t _internal_ret1() const;
  void _internal_set_ret1(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rpc.AddMethod)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t arg1_;
    int32_t arg2_;
    int32_t ret1_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_add_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddMethod

// int32 arg1 = 1;
inline void AddMethod::clear_arg1() {
  _impl_.arg1_ = 0;
}
inline int32_t AddMethod::_internal_arg1() const {
  return _impl_.arg1_;
}
inline int32_t AddMethod::arg1() const {
  // @@protoc_insertion_point(field_get:rpc.AddMethod.arg1)
  return _internal_arg1();
}
inline void AddMethod::_internal_set_arg1(int32_t value) {
  
  _impl_.arg1_ = value;
}
inline void AddMethod::set_arg1(int32_t value) {
  _internal_set_arg1(value);
  // @@protoc_insertion_point(field_set:rpc.AddMethod.arg1)
}

// int32 arg2 = 2;
inline void AddMethod::clear_arg2() {
  _impl_.arg2_ = 0;
}
inline int32_t AddMethod::_internal_arg2() const {
  return _impl_.arg2_;
}
inline int32_t AddMethod::arg2() const {
  // @@protoc_insertion_point(field_get:rpc.AddMethod.arg2)
  return _internal_arg2();
}
inline void AddMethod::_internal_set_arg2(int32_t value) {
  
  _impl_.arg2_ = value;
}
inline void AddMethod::set_arg2(int32_t value) {
  _internal_set_arg2(value);
  // @@protoc_insertion_point(field_set:rpc.AddMethod.arg2)
}

// int32 ret1 = 3;
inline void AddMethod::clear_ret1() {
  _impl_.ret1_ = 0;
}
inline int32_t AddMethod::_internal_ret1() const {
  return _impl_.ret1_;
}
inline int32_t AddMethod::ret1() const {
  // @@protoc_insertion_point(field_get:rpc.AddMethod.ret1)
  return _internal_ret1();
}
inline void AddMethod::_internal_set_ret1(int32_t value) {
  
  _impl_.ret1_ = value;
}
inline void AddMethod::set_ret1(int32_t value) {
  _internal_set_ret1(value);
  // @@protoc_insertion_point(field_set:rpc.AddMethod.ret1)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_add_2eproto
